# Generated by Django 4.0.6 on 2023-02-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='email',
            new_name='Reg_email',
        ),
    ]
